export const GETBOOKDETAIL_REQUEST = "GETBOOKDETAIL_REQUEST"
export const GETBOOKDETAIL_SUCCESS = "GETBOOKDETAIL_SUCCESS"
export const GETBOOKDETAIL_ERROR = "GETBOOKDETAIL_ERROR"

export const AMOUNT = "AMOUNT"