export const GETLISTBOOK_REQUEST = "GETLISTBOOK_REQUEST"
export const GETLISTBOOK_SUCCESS = "GETLISTBOOK_SUCCESS"
export const GETLISTBOOK_ERROR = "GETLISTBOOK_ERROR"

export const SEARCH_BOOK = "SEARCH_BOOK"
export const AUTHOR = "AUTHOR"